viamrobotics/prime

package.json, src/elements/select/select.svelte
**20221005_Change background of v-select input to white**
Do you mind if I change the background of the v-select input from transparent to white?
Otherwise the v-select I'm using on the robots page for new parent will be grey :(
=> Change background of v-select input to white

package-lock.json, package.json, src/elements/radio.svelte
=> radio options will not wrap now

src/elements/breadcrumbs.svelte, src/elements/collapse.svelte, src/elements/dropdown.svelte, src/elements/modal.svelte
This makes PRIME more responsive. See examples [here](https://viam.atlassian.net/browse/APP-887).
=> App 887 responsiveness

package-lock.json, package.json, src/elements/collapse.svelte
=> fix vertical alignment

package-lock.json, package.json, src/elements/select/select.svelte
Adding the accessibility key press handlers caused a problem. This fixes that.
=> bugfix for enter key handler

package-lock.json, package.json, src/elements/collapse.svelte, src/stories/collapse.stories.mdx
This PR adds a variant of v-collapse such that there is no border and there is no background color
=> variant of collapse

package-lock.json, src/elements/collapse.svelte
make background white only on default for v-collapse
=> make background white only on default

package-lock.json, package.json, src/elements/select/multiselect.svelte
Currently when one selects 2nd or later option the component renders tags which shifts the layout causing one to select the 1st or previous option.
https://user-images.githubusercontent.com/17263/207711685-6c092a0d-7ccd-4a74-97e4-81b1fa5887b6.mov
=> Prevent layout shift select

package-lock.json, package.json, src/elements/button/button.svelte
Quick fix to the inverse primary button border color so it renders properly.
=> Fix inverse primary button border

package-lock.json, package.json, src/elements/select/multiselect.svelte
Multiselect was not clearing all without the parent modifying the value. Internally changes the value to `''` on clear
=> Multiselect clear all bug

package-lock.json, package.json, src/elements/select/multiselect.svelte
fix bug error where the array was not reducing correctly when empty string was passed in and sortoption='off'
=> [DATA-995] Empty string check in multiselect

package-lock.json, package.json, src/elements/switch.svelte
=> Switches update: Set width of clickable label to fit content rather than full width.

package-lock.json, package.json, playground/src/App.vue, src/elements/button/button.svelte
updating what the button looks like when disabled so it works for all variants.
=> update button disabled

src/elements/radio.svelte, src/stories/radio.stories.mdx
Fix an issue where label position was not working as intended and added some additional story options.
=> Fix radio label position and add more options to stories

tests/input.spec.ts, tests/multi-select.spec.ts
Fix 2 bugs in input and multi-select tests, see conversation in #213
=> Fix failing tests revealed by fixing custom event helpers

.storybook/manager-head.html, .storybook/preview-head.html, .storybook/theme.js, package-lock.json, package.json, prime.css, src/elements/breadcrumbs.svelte, src/elements/collapse.svelte, src/elements/input/input.svelte, src/elements/notify.svelte, src/elements/radio.svelte, src/elements/select/multiselect.svelte, src/elements/select/select.svelte, src/elements/tabs.svelte, src/stories/button.stories.mdx, src/stories/collapse.stories.mdx, src/stories/input.stories.mdx, src/stories/multiselect.stories.mdx, src/stories/notify.stories.mdx, src/stories/select.stories.mdx, tests/badge.spec.ts, tests/button.spec.ts, tests/icon.spec.ts, tests/notify.spec.ts
This PR was done after another design sync with Nat + Jason. Changes:
* Notify element now has an action slot for buttons. This was done for upcoming billing features.
* PRIME now makes no opinions about fonts, this was done to transition us gracefully to Public Sans.
* Input labels are now only first letter capitalized
* Storybook fonts are changed to Public Sans
* Various smaller design syncs
=> Update fonts and design sync

package-lock.json, package.json
thought I updated in Data-1365 but it didn't update
=> update package.json version

package-lock.json, package.json, src/elements/notify.svelte
Remove relative parent and absolutely positioned child to avoid z-index issue on app.
=> fix z-index issue

package.json, playground/src/switch-test.vue, src/elements/breadcrumbs.svelte, src/elements/button/button.svelte, src/elements/input/input.svelte, src/elements/list-box.svelte, src/elements/modal.svelte, src/elements/radio.svelte, src/elements/select/multiselect.svelte, src/elements/select/select-button.svelte, src/elements/select/select.svelte, src/elements/slider.svelte, src/elements/switch.svelte, src/elements/table/table.svelte, src/elements/table/th.svelte, src/elements/tabs.svelte, src/stories/button.stories.mdx, src/stories/select.stories.mdx, src/stories/switch.stories.mdx, tests/multi-select.spec.ts, tests/select.spec.ts, tests/switch.spec.ts, tests/table.spec.ts
* Align font sizes and padding sizes with figma
* Remove capitalization rules to allow for first letter only capitalized statements
* Add pressed states to buttons
* Add hover and pressed states to icon buttons
* Align some background colors with figma
=> Design sync May 10 2023

playwright.config.ts, tests/breadcrumbs.spec.ts, tests/button.spec.ts, tests/code-editor.spec.ts, tests/collapse.spec.ts, tests/icon.spec.ts, tests/input.spec.ts, tests/lib/helper.spec.ts, tests/lib/helper.ts, tests/list-box.spec.ts, tests/modal.spec.ts, tests/multi-select.spec.ts, tests/notify.spec.ts, tests/radio.spec.ts, tests/select.spec.ts, tests/slider.spec.ts, tests/switch.spec.ts, tests/table.spec.ts, tests/tabs.spec.ts
This PR fixes all lint warnings in test files. Broke apart test file changes and `src` changes for safety
=> Fix lint warnings in test files

package-lock.json, package.json, src/elements/button/button.svelte, src/elements/collapse.svelte, src/elements/pill.svelte
https://viam.atlassian.net/browse/APP-1657
=> App 1657 design maintenance

package-lock.json, package.json, playground/context-menu-test.html, playground/src/context-menu-test.vue, playground/src/pages/context-menu-test.ts, src/elements/context-menu/context-menu-item.svelte, src/elements/context-menu/context-menu-separator.svelte, src/elements/context-menu/context-menu.svelte, src/main.ts, src/stories/context-menu.stories.mdx, tests/context-menu.spec.ts
Context menu represents the menu itself -- any positioning / floating behavior must be externally managed (see test example)
design https://www.figma.com/file/ERHSYDGTXiEQOVGY8ORg6I/PRIME?type=design&node-id=2703-5151&t=PUd4XMOf36ba4gDT-0
=> APP-1844 Create context menu component

package-lock.json, package.json
this is to use the new `context-menu` component
=> I forgot to bump the prime version

package-lock.json, package.json, src/elements/button/button.svelte, src/elements/slider.svelte
UI design maintenance tasks
https://viam.atlassian.net/browse/APP-1929
=> APP-1929 design updates

package-lock.json, package.json, playground/src/tabs-test.vue, src/elements/code-snippet.svelte, src/stories/assets/json-code-example.js
Bugfix -- call highlight code function on mount.
https://github.com/viamrobotics/prime/assets/17263/54450b94-4214-4996-a4ba-ff497fdd7a6c
This also fixes a layout issue when there is only one line in code.
=> onMount fix

package-lock.json, package.json, src/elements/code-snippet.svelte
Notify user when text is copied to clipboard and of failure if necessary.
https://github.com/viamrobotics/prime/assets/17263/813c37f1-3c6c-48fc-9095-307c931ef3b6
=> App 1990 code snippet copy

package-lock.json, package.json, src/elements/code-snippet.svelte
Override the font used by prism.js to match our styles. This had to be done in JS.
=> override font

src/elements/code-snippet.svelte
Fix reactivity for code snippet value.
Relates to https://github.com/viamrobotics/app/pull/1853#issuecomment-1582654754
=> App 1990 code snippet reactivity

package-lock.json, package.json
Bumping Prime for code snippets.
=> bump prime version

.storybook/main.ts, package-lock.json, package.json, playground/src/vue.d.ts, playground/tsconfig.json, src/elements/code-snippet.svelte, src/elements/notification/container.component, src/elements/notification/index.ts, src/elements/notification/item.component, src/elements/notification/stores.ts, src/elements/notify.svelte, src/lib/notify.ts, src/main.ts, src/stories/notification.stories.ts, src/vite-env.d.ts, svelte.config.js, tailwind.config.ts, vite.config.ts
This PR adds the bare minimum features to allow us to replace our third party toast library. Adding additional features to achieve [designs here](https://www.figma.com/file/ERHSYDGTXiEQOVGY8ORg6I/PRIME?type=design&node-id=326-5342&t=Yq8OTOH0KjrQcE8Z-0) will be added in later PRs.
=> Add basic notify features

package-lock.json, package.json, playground/src/tabs-test.vue, src/elements/code-snippet.svelte
Code snippet currently is not reactive, despite binding.
=> Bug fix: code snippet reactivity

package-lock.json, package.json, playground/src/tabs-test.vue, src/elements/code-snippet.svelte
Update layout for single line snippets.
=> App 1986 UI design maintenance

package-lock.json, package.json, src/elements/switch.svelte
https://viam.atlassian.net/browse/APP-2069
Clicking on labels is not triggering desired event.
=> Switch component fix -- event handlers for labels and switch button

package-lock.json, package.json, playground/src/tabs-test.vue, src/elements/code-snippet.svelte, src/stories/assets/cpp-code-example.js
bug fix: format string before highlighting, converting to special html entities
=> App 2068 bugfix code snippet

package-lock.json, package.json, src/elements/code-snippet.svelte
In app there's an error occurring that does not occur in playground or storybook.
`prime.js:2787 Uncaught TypeError: Cannot read properties of undefined (reading 'replaceAll')`
=> App 2068 bugfix undefined replace

package.json
Bumping Prime version as I forgot to with https://github.com/viamrobotics/prime/pull/259
=> bump prime

package.json, src/elements/code-editor/code-editor.svelte, src/elements/code-snippet.svelte, src/elements/collapse.svelte, src/elements/context-menu/context-menu-item.svelte, src/elements/dropdown.svelte, src/elements/input/input.svelte, src/elements/list-box.svelte, src/elements/modal.svelte, src/elements/notify.svelte, src/elements/pill.svelte, src/elements/radio.svelte, src/elements/select/multiselect.svelte, src/elements/select/select.svelte, src/elements/slider.svelte, src/elements/switch.svelte, src/elements/tabs.svelte, src/elements/vector-input.svelte, src/lib/dispatch.ts
This fixes a dispatch problem, preventing propagation on native elements...
=> dispatch fixes

package.json, src/elements/icon/icons.ts, src/stories/icon.stories.mdx
added 4 additional icons, expand left right, collapse left right
=> Add arrow icons

package.json, src/elements/button/button.svelte, src/elements/icon/icon.svelte, src/elements/select/select.svelte, tests/context-menu.spec.ts, tests/select.spec.ts
Adjustment to icon layout and colors.
=> bugfix: colors and layout

README.md, package.json, playground/src/App.vue, playground/src/button-test.vue, src/elements/button/button.svelte, src/elements/radio.svelte, src/stories/button.stories.mdx, src/stories/radio.stories.mdx, tests/button.spec.ts
add a `width` field to both `v-button` and `v-radio` to allow the elements to stretch the full width of its container
=> [DATA-1742] Add full width option to button and radio

package.json
version bump for last updates to show up
=> version bump for last commit

packages/legacy/package.json, packages/legacy/src/elements/button/button.svelte, packages/legacy/src/elements/collapse.svelte, packages/legacy/src/elements/context-menu/context-menu-item.svelte, packages/legacy/src/elements/icon/icon.svelte, packages/legacy/src/elements/select/multiselect.svelte, packages/legacy/src/elements/select/select.svelte, packages/legacy/src/stories/icon.stories.mdx, packages/legacy/src/stories/multiselect.stories.mdx, packages/legacy/tests/icon.spec.ts
Various layout fixes from @nathartman
=> Layout fixes

packages/legacy/package.json, packages/legacy/src/elements/button/button.svelte, packages/legacy/src/elements/code-snippet.svelte, packages/legacy/src/elements/context-menu/context-menu-item.svelte, packages/legacy/src/elements/icon/icon.svelte, packages/legacy/src/elements/input/input.svelte, packages/legacy/src/elements/list-box.svelte, packages/legacy/src/elements/notify.svelte, packages/legacy/src/elements/radio.svelte, packages/legacy/src/elements/select/multiselect.svelte, packages/legacy/src/elements/select/select.svelte, packages/legacy/src/stories/button.stories.mdx, packages/legacy/src/stories/icon.stories.mdx, packages/legacy/tests/notify.spec.ts
Rather than explicitly setting the icon color every time, inherit from parent, or overwrite with text color.
=> inherit fill color from text-color

packages/core/src/lib/button.svelte, packages/legacy/package.json, packages/legacy/src/elements/button/button.svelte, packages/legacy/src/elements/code-snippet.svelte, packages/legacy/src/elements/context-menu/context-menu-item.svelte, packages/legacy/src/elements/icon/icons.ts, packages/legacy/src/elements/notify.svelte, packages/legacy/src/elements/select/multiselect.svelte, packages/legacy/src/elements/select/select.svelte, packages/legacy/src/elements/switch.svelte, packages/legacy/tests/notify.spec.ts
design maintenance 7/28/2023 with @nathartman
=> Design maintenance 

packages/storybook/.eslintignore, packages/storybook/.prettierignore
Quick one found in development. The storybook output shouldn't get formatted or checked!
=> Add storybook output to eslintignore and prettierignore

packages/core/src/lib/index.ts, packages/core/src/lib/pill.spec.ts, packages/core/src/lib/pill.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/pill.stories.mdx
Migrates Pill component to `@viamrobotics/prime-core`.
- Copy `pill.svelte` to `packages/core`
- Added docstrings
- Add `Pill` export from `index.ts`
- Copy unit tests
- Change to use vitest
- Copy storybook story to `packages/storybook`
- Change to use Svelte component directly
- No icons yet - [APP-2290](https://viam.atlassian.net/browse/APP-2290)
- Need to be added later
- Added unit tests
- None
[APP-2290]: https://viam.atlassian.net/browse/APP-2290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> APP-2296 Migrate pill to @viamrobotics/prime-core

packages/legacy/package.json, packages/legacy/src/elements/switch.svelte
This fix is related to https://github.com/viamrobotics/prime/pull/292
=> Bug fix: <v-switch> events

packages/core/src/lib/label.spec.svelte, packages/core/src/lib/label.spec.ts, packages/core/src/lib/label.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/label/label.stories.mdx, packages/storybook/src/stories/label/with-input.svelte
Adding some uncommitted changes from the last PR.
=> APP-2291 Add label to core follow-up

packages/core/package.json
I'm going to start using some of the migrated components in the new Svelte App. Woohoo!
=> Bump version for @viamrobotics/prime-core

packages/core/package.json, pnpm-lock.yaml
These dependencies were missing at runtime.
Tested by linking locally into app.
=> Make classnames and @mdi/js required dependencies

packages/core/package.json
=> Bump PRIME core version

packages/core/package.json
Bumping core package version for app
=> bump core version

packages/core/package.json, packages/core/theme.ts
This theme will be used by app - this adds the missing expand-vertical transition property.
=> APP-2412 Add expand-vertical to theme

packages/core/package.json
=> Bump @viamrobotics/prime-core to v0.0.15

packages/blocks/package.json, packages/blocks/src/lib/navigation-map/components/map.svelte, packages/blocks/src/lib/navigation-map/components/nav/index.svelte, packages/blocks/src/lib/navigation-map/components/scene.svelte, packages/blocks/src/lib/navigation-map/index.svelte, packages/blocks/src/lib/navigation-map/stores.ts, packages/blocks/src/lib/navigation-map/types.ts, packages/blocks/src/routes/navigation-map.svelte
A small collection of `<NavigationMap>` tweaks based on updated designs:
* Add a slot for a custom tab
* Update tab styles
* Fix a bug where axes would render with no obstacles
* Bump up lighting of obstacles a bit
=> Navigation map tweaks

packages/core/package.json, packages/core/src/lib/__tests__/pill.spec.ts, packages/core/src/lib/button/button.svelte, packages/core/src/lib/button/icon-button.svelte, packages/core/src/lib/icon/icon.svelte, packages/core/src/lib/index.ts, packages/core/src/lib/pill.svelte, packages/core/src/lib/select/__tests__/multiselect.spec.ts, packages/core/src/lib/select/controls.ts, packages/core/src/lib/select/dispatcher.ts, packages/core/src/lib/select/multiselect.svelte, packages/core/src/lib/select/searchable-select.svelte, packages/core/src/lib/select/select-input.svelte, packages/core/src/lib/select/select-menu.svelte, packages/core/src/lib/select/select.svelte, packages/core/src/lib/switch.svelte, packages/core/src/routes/+page.svelte, packages/core/theme.ts, packages/storybook/src/stories/select/labeled-multiselect.svelte, packages/storybook/src/stories/select/multiselect.stories.mdx
=> Add multiselect

packages/core/package.json, packages/core/src/lib/button/button.svelte, packages/core/src/routes/+page.svelte
Ghost buttons should always have the icon `text-gray-6` and text `text-default`.
=> App 2206 ghost button

packages/core/package.json, packages/core/src/lib/__tests__/badge.spec.ts, packages/core/src/lib/__tests__/banner.spec.svelte, packages/core/src/lib/__tests__/banner.spec.ts, packages/core/src/lib/__tests__/breadcrumbs.spec.ts, packages/core/src/lib/__tests__/cx-test.ts, packages/core/src/lib/__tests__/label.spec.svelte, packages/core/src/lib/__tests__/label.spec.ts, packages/core/src/lib/__tests__/pill.spec.ts, packages/core/src/lib/__tests__/tabs.spec.ts, packages/core/src/lib/badge.svelte, packages/core/src/lib/button/__tests__/button.spec.ts, packages/core/src/lib/button/__tests__/icon-button.spec.ts, packages/core/src/lib/context-menu/__tests__/context-menu.spec.svelte, packages/core/src/lib/context-menu/__tests__/context-menu.spec.ts, packages/core/src/lib/icon/__tests__/icon.spec.ts, packages/core/src/lib/input/__tests__/input.spec.ts, packages/core/src/lib/input/__tests__/numeric-input.spec.ts, packages/core/src/lib/input/__tests__/slider-input.spec.ts, packages/core/src/lib/input/__tests__/text-input.spec.ts, packages/core/src/lib/select/__tests__/multiselect.spec.ts, packages/core/src/lib/select/__tests__/searchable-select.spec.ts, packages/core/src/lib/select/__tests__/select.spec.ts, packages/core/src/lib/select/multiselect.svelte, packages/core/src/lib/select/searchable-select.svelte, packages/core/src/lib/table/__tests__/table.spec.svelte, packages/core/src/lib/table/__tests__/table.spec.ts
Noticed some bugs with the `cx` props I added so added some tests and fixes.
=> cx tests and fixes

packages/storybook/src/stories/badge.stories.mdx, packages/storybook/src/stories/breadcrumbs.stories.mdx, packages/storybook/src/stories/icon/icon.stories.mdx, packages/storybook/src/stories/pill.stories.mdx, packages/storybook/src/stories/tabs.stories.mdx, packages/storybook/src/stories/vector-input.stories.mdx
Some incorrect imports slipped through - I checked them all and every story seems to render correctly now!
=> Fix some cx imports

packages/core/package.json, packages/core/src/lib/index.ts, packages/legacy/src/lib/notify.ts
=> APP-2703: add missing `Notify` type export

packages/core/README.md
Starting to bring in things from https://github.com/viamrobotics/prime/pull/357 starting with this doc change. Feel free to leave edits as suggestions.
=> Add anatomy of a component to README

packages/blocks/src/lib/maplibre/marker.svelte, packages/blocks/src/lib/navigation-map/components/robot-marker.svelte, packages/blocks/src/lib/navigation-map/components/waypoints.svelte
https://viam.atlassian.net/browse/RSDK-4395
We change the robot-marker icon.
To do this, we add the following properties to the `MapMarkerLibre` class:
1. `(property) icon: HTMLElement`. With this we can define what icon we want the marker to use with an SVG url.
2. `(property) rotation?: number`. With this we can define the rotation of the marker. Here 0 is north and 90 is east.
=> RSDK-4395 - Update RC UI to show compass heading of robot

packages/core/package.json, packages/core/src/lib/index.ts, packages/core/src/lib/list-box.svelte, packages/core/src/lib/list-box/__tests__/list-box.spec.ts, packages/core/src/lib/list-box/list-box-slot.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/list-box.mdx, packages/storybook/src/stories/list-box.stories.svelte
Migrating List box to Prime Core, updated the svelte files to have native dispatcher and booleans as well as updated story books, tests etc...
=> APP-2292 - ListBox core migration

packages/core/package.json, packages/core/src/lib/icon/icons.ts
=> add icon, upgrade

packages/blocks/package.json, packages/blocks/src/lib/navigation-map/components/nav/obstacles.svelte, packages/core/package.json, packages/core/src/lib/input/slider-input.svelte
Fixes two minor issues:
* Blocks: fixes an issue where the delete obstacle button was appearing outside configure mode
* Core: fixes z-index and slider offset issues with the slider input
=> [APP-2891] Fix slider input visual bugs

packages/core/package.json, packages/core/src/lib/badge.svelte, packages/core/src/lib/banner/banner.svelte, packages/core/src/lib/button/icon-button.svelte, packages/core/src/lib/pill.svelte, packages/core/theme.ts
* Fix incorrect theme value
* Fix badge dimensions
* Fix pill dimensions and hover state
* Fix danger and disabled icon button hover state
=> Design maintenance October 25

packages/core/package.json, packages/core/src/lib/context-menu/context-menu-item.svelte
- Updates context menu item gap to 1.5 (6px)
- Updates context menu item horizontal padding to 3 (12px)
=> Update context menu style per R2D2 designs

packages/core/package.json, packages/core/src/lib/__tests__/badge.spec.ts, packages/core/src/lib/badge.svelte, packages/core/src/lib/icon/icons.ts, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/badge.stories.svelte
One simple thing here: align badges with our semantic names!
When this is merged I'll open PRs downstream updating all our badges.
=> Design maintenance - November 21

packages/core/package.json, packages/core/src/lib/banner/__tests__/banner.spec.svelte, packages/core/src/lib/banner/__tests__/banner.spec.ts, packages/core/src/lib/banner/banner.svelte, packages/core/src/lib/notification/notification-item.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/banner.stories.svelte
PRIME update
- deprecates `message` slot in lieu of `subtitle` slot.
- new `actionEmphasize` slot for use with Buttons.
- margin adjustments for `action` vs `actionEmphasize` slots
- storybook docs improvements
_APP changes required after update. Replace `message` attributes with `subtitle`_
=> Design maintenance nov 30 2023

packages/blocks/package.json, packages/blocks/src/lib/navigation-map/components/map.svelte
It does the things! I didn't switch from a div to a different element and opted to silence the a11y error instead. Let me know if you agree or if I should switch to a different element.
=> Nav map - stop following base on mouse or wheel interaction

packages/blocks/package.json, packages/blocks/src/lib/index.ts, packages/blocks/src/lib/navigation-map/components/path.svelte, packages/blocks/src/lib/navigation-map/components/scene.svelte, packages/blocks/src/lib/navigation-map/index.svelte, packages/blocks/src/lib/navigation-map/stores.ts, packages/blocks/src/lib/navigation-map/types.ts, packages/blocks/src/routes/navigation-map.svelte
Improvements to the rendering of paths in the navigation map!
- Rename `Plan` to `Path` - this is consistent with motion team's terminology
- Render smaller spheres and dashes
- Get rid of the concept of "previous" paths - this doesn't exist in the `GetPaths` RPC
=> RSDK-4825: Improvements to nav map paths

packages/core/package.json, packages/core/src/lib/icon/icons.ts
- Adds new icon to replace our current robot icon.
- Needed for "robot" to "machine" string updates on app's fe.
- https://pictogrammers.com/library/mdi/icon/multiplication-box/
=> Add machine icon

.github/actions/setup/action.yml
=> Revert remove setup action

README.md, packages/core/package.json, packages/core/src/lib/button/icon-button.svelte, packages/core/src/lib/icon/icon.svelte, packages/storybook/src/stories/banner.mdx, packages/storybook/src/stories/banner.stories.svelte, packages/storybook/src/stories/code-snippet.stories.svelte, packages/storybook/src/stories/context-menu.mdx, packages/storybook/src/stories/context-menu.stories.svelte, packages/storybook/src/stories/icon-button.mdx, packages/storybook/src/stories/icon-button.stories.svelte, packages/storybook/src/stories/input.mdx, packages/storybook/src/stories/input.stories.svelte
Inaugural Storybook design maintenance. Good work, team.
Next time: go over inputs again, then continue alphabetically
- Remove title from `IconButton`
- Fix hover for danger `IconButton`
- Default icons to `text-gray-6`
- Lots of storybook updates
=> 2023-12-20 Storybook design maintenance

packages/core/package.json, packages/core/src/lib/__tests__/radio.spec.ts, packages/core/src/lib/input/numeric-input.svelte, packages/core/src/lib/radio.svelte, packages/storybook/src/stories/input.mdx, packages/storybook/src/stories/input.stories.svelte, packages/storybook/src/stories/label.mdx, packages/storybook/src/stories/modal.mdx, packages/storybook/src/stories/modal.stories.svelte, packages/storybook/src/stories/pill.mdx, packages/storybook/src/stories/pill.stories.svelte, packages/storybook/src/stories/radio.mdx, packages/storybook/src/stories/radio.stories.svelte
- Numeric input placeholder
- Radio style updates
- Many storybook updates
=> 2024-01-10 PRIME design maintenance

packages/core/package.json, packages/core/src/lib/icon/icons.ts
Used for registry module header in https://viam.atlassian.net/browse/APP-3295
=> Add link-variant icon

packages/blocks/package.json, packages/blocks/src/vitest.setup.ts, packages/blocks/vite.config.ts, packages/core/package.json, packages/core/src/vitest.setup.ts, packages/core/vite.config.ts, pnpm-lock.yaml
Companion PR to viamrobotics/app#3492
=> Ensure browser version of Svelte is used in tests

packages/core/package.json, packages/core/src/lib/icon/icons.ts
Adds the OS icons and cleans up the icon map name ordering for sanity.
=> Add OS icons

packages/core/package.json, packages/core/src/lib/button/__tests__/icon-button.spec.ts, packages/core/src/lib/button/icon-button.svelte, packages/core/src/lib/code-snippet.svelte, packages/storybook/src/stories/icon-button.mdx, packages/storybook/src/stories/icon-button.stories.svelte
- Update font size for code snippet
- Add `IconButton` "secondary" variant
=> Design maintenance prime 14 feb 2024

packages/core/package.json
prime core package was missing the plugins.ts file
=> add plugin file to build

packages/core/package.json, packages/core/src/lib/icon/__tests__/icon.spec.ts, packages/core/src/lib/icon/icon.svelte, packages/core/src/lib/select/__tests__/search.spec.ts, packages/core/src/lib/select/__tests__/searchable-select.spec.ts, packages/core/src/lib/select/multiselect.svelte, packages/core/src/lib/select/search.ts, packages/core/src/lib/select/searchable-select.svelte, packages/core/src/lib/select/select-input.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/select.stories.svelte
Ticket: https://viam.atlassian.net/browse/APP-4295
Designs: https://www.figma.com/file/ERHSYDGTXiEQOVGY8ORg6I/PRIME?type=design&node-id=4732-503&mode=design&t=szARlyFbXZV6gpkv-11
Review Requests:
Please check out this branch so and manually sanity check with `pnpm dev` (it is on viamrobotics/prime so it should be easy). Despite adding tests, this is still very fragile & complex code.  
If you find bugs, happy to talk through them in person or via zoom with Kurt or I
Will add the prime core version bump before merge.
=> APP-4295 - Searchable Select With Descriptions and Icons

packages/core/package.json, packages/core/src/lib/icon/icons.ts
add article icon, needed for r2d2
=> add article icon

packages/core/package.json, packages/core/src/lib/icon/icons.ts, packages/core/src/routes/+page.svelte
=> add application-outline icon

packages/core/package.json, packages/core/src/lib/icon/icons.ts
Adds file chart outline mdi icon.  Will be needed for linking components to filtered data view ticket.
=> APP-3047: Add file chart outline icon

packages/core/package.json, packages/core/src/lib/icon/icons.ts
Adds script text outline mdi icon. Will be needed for training script view ticket.
=> DATA-2450: Add script text outline icon

packages/core/package.json, packages/core/src/lib/button/button.svelte, packages/core/src/lib/button/progress.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/button.mdx, packages/storybook/src/stories/button.stories.svelte
=> Add loading process indicator option to button

packages/core/package.json, packages/core/src/lib/button/button.svelte, packages/core/src/lib/button/progress.svelte, packages/core/src/routes/+page.svelte
=> design maintenance - Button indeterminant button variant

packages/core/package.json, packages/core/src/lib/icon/icons.ts
=> APP-4732: Add expand/collapse icons

packages/core/package.json, packages/core/src/lib/icon/icons.ts
For: https://www.figma.com/design/GSi2nRrsKHQnP2uYNx5XMK/Make-UI-Not-Shitty-II?node-id=11380-45941&t=I3BvUfFBRVYctLzR-0
MDI Pause: https://pictogrammers.com/library/mdi/icon/pause/
=> Add MDI Pause Icon

packages/core/package.json, packages/core/src/lib/progress/progress.svelte
=> Progress fix

packages/blocks/package.json, packages/blocks/src/lib/maplibre/index.svelte, packages/blocks/src/routes/following-marker.svelte
Not a breaking change since the navigation map does not use this prop.
=> Make maplibre center prop reactive

packages/core/package.json, packages/core/src/lib/button/icon-button.svelte, packages/core/src/lib/progress/progress.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/icon-button.mdx, packages/storybook/src/stories/icon-button.stories.svelte
=> Add progress to icon button

packages/core/package.json, packages/core/src/lib/tooltip/tooltip-text.svelte
Fixes `Tooltip` word break issue.
=> Bug fix: `word-break`: `break-word` replaces `break-all`

packages/core/package.json, packages/core/src/lib/__tests__/pill.spec.ts, packages/core/src/lib/pill.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/pill.mdx, packages/storybook/src/stories/pill.stories.svelte
=> add new link option for pills

packages/core/package.json, packages/core/src/lib/icon/icons.ts
Add file swap icon to support transfer registry item ownership feature.
=> APP-5180 Add file swap icon

packages/core/package.json, packages/core/src/lib/icon/icons.ts
=> APP-5435: add picture in picture icon

packages/core/package.json, packages/core/src/lib/icon/icon.svelte, packages/core/src/lib/icon/icons.ts, packages/core/src/lib/pill.svelte, packages/core/src/lib/select/__tests__/searchable-select.spec.ts, packages/storybook/src/stories/icon.stories.svelte
- Add `toggle-switch-outline` and `toggle-switch-off-outline` icons
- Ensure icon names are strictly typed, not `string`
=> APP-5548: add toggle icons, fix icon name type-checking

packages/core/package.json, packages/core/src/lib/icon/icons.ts
Add `layers-triple-outline` icon.
=> add layers-triple-outline icon

packages/core/package.json, packages/core/src/lib/button/icon-button.svelte
Secondary `IconButton` should have border.
=> Design maintenance prime aug 21 2024

packages/core/package.json, packages/core/src/lib/icon/icons.ts, packages/core/src/lib/modal.svelte, packages/core/src/routes/+page.svelte
=> add modal medium variant, add export icon

packages/core/package.json, packages/core/src/lib/modal.svelte, packages/legacy/src/elements/modal.svelte
- Remove `max-width` on modal container. This fixes a problem with the `medium` variant.
=> Data 2978 add modal variant fix

.github/workflows/ci.yml
=> ci: use Node v20 in publish job

packages/core/package.json, packages/core/src/lib/button/button.svelte, packages/core/src/lib/input/input.svelte, packages/core/src/lib/input/range-input.svelte
design-maintenance-aug-28-2024
=> design maintenance: support interim dark mode state of prime

packages/blocks/package.json, packages/blocks/src/lib/navigation-map/components/nav/index.svelte
Drive-by fix for phantom scrollbars in the navigation service card
=> Fix: s/overflow-y-scroll/overflow-y-auto/

packages/core/package.json, packages/core/src/lib/button/button.svelte
=> fix text color for danger-outline variant button

packages/core/package.json, packages/core/src/lib/input/input.svelte
Read only input should have grey background
=> fix bug: background color of disabled input

packages/blocks/package.json, packages/blocks/src/lib/maplibre/controls/follow.svelte, packages/blocks/src/lib/navigation-map/components/map.svelte
This PR simply exposes a `following` prop on `<FollowControls>`, allowing the following behavior to be turned on by default until a user interacts or turns it off.
=> Maplibre `<FollowControls>` component - expose following prop

.github/workflows/ci.yml
=> Deps: bump upload/download artifact actions in CI workflow

.github/workflows/ci.yml
=> CI: grab missing actions/download-artifact bump

packages/core/package.json, packages/core/src/lib/__tests__/code-snippet.spec.ts, packages/core/src/lib/code-snippet.svelte, packages/core/src/lib/icon/icons.ts, pnpm-lock.yaml
Grab bag of tasks
- add bug outline icon (for enable debug logs)
- add reactivity to `CodeSnippet` element
- update `@testing-library/svelte`
=> Add bug outline icon and add reactivity to `CodeSnippet` element 

packages/core/package.json
=> forgot to bump prime version

packages/core/package.json, packages/core/src/lib/icon/icons.ts
New **indeterminate** checkbox ⭐ 
Manually added path value. mdi package does not have the right design.
=> DATA-3600 Add indeterminate checkbox

packages/core/package.json, packages/core/src/lib/icon/icons.ts
=> APP-7271 Add fragment versions icon

packages/core/package.json, packages/core/src/lib/icon/icons.ts
The indeterminate checkbox was ever so slightly not a square. So I had Nat fix it up
=> DATA-3600 Tweak checkbox path

packages/core/package.json, packages/core/src/lib/icon/icons.ts
=> DATA-3634 Add clock outline icon

packages/core/package.json, packages/core/src/lib/modal.svelte
Otherwise there is no way to specify a custom max size for the content. It will always have a max h and w.
=> Add modal variant for fitting size to content

packages/core/package.json, packages/core/src/lib/icon/icons.ts
New text search icon! Much wow.
=> DATA-3604 Add text-search icon
