package.json, src/elements/switch.svelte, src/stories/switch.stories.mdx
**20221024_Add tooltip to v-switch**
**Items to Note:**
- This PR adds a tooltip to the v-switch PRIME element.
- I need this for the remotes tab in app.
=> Add tooltip to v-switch

src/elements/button/button.svelte, src/lib/dispatch.ts
Adds a click handler to the v-button that prevents the click handler attached at point of implementation from being invoked. `stopImmediatePropagation` stops event handlers of the same type added after from being invoked - can then choose to dispatch (proceeding with the propagation) if the input is not disabled. Also adds a new dispatcher that copies the dispatch event, allowing the event to pass through as the correct type.
=> prevents v-button from being invoked when disabled

package-lock.json, package.json, src/elements/collapse.svelte
Currently items inside v-collapse are getting clipped. This removes overflow-hidden.
=> remove overflow-hidden on collapse component

package-lock.json, package.json, playground/src/App.vue, src/elements/select/multiselect.svelte, src/elements/select/select-button.svelte, src/elements/select/select.svelte, src/elements/select/utils.ts, src/lib/sort.ts, src/main.ts, src/stories/multiselect.stories.mdx, src/stories/select.stories.mdx
Functionalities included in this PR:
- added `dosearch` prop, if false, then sort will not be done within component
- added `reducesort` prop, if true, will only show matching results instead of priority listing
- split up v-select to a separate v-multiselect which has functionalities that only apply to multi select. The select component will be refactored in the future to only have single select features
- add `heading` prop, if has value, then will show a heading within the dropdown
heading preview:
=> [DATA-804] add reduce sort to select, split out multi-select

package-lock.json, package.json, src/elements/select/multiselect.svelte, src/stories/multiselect.stories.mdx
Adding a bunch of new event types (enter-press, open, close) and allowing search term to be controlled. We want to be able to manipulate the search term at the point of implementation as needed for a variety of things like programmatically clearing the term or lowercasing.
There was also a bug where an having an empty array would prevent the search event from dispatching - this also fixes that by having the `handleInput` dispatch the event immediately rather than being contingent upon the search being applied
=> Adds new event types and makes search term a controlled input

package-lock.json, package.json, src/elements/select/multiselect.svelte, src/elements/select/utils.ts
Oops another fix! When displaying checked/unchecked value, was checking to see if the option was in the stringified list of values which meant that if you had the value set to `"gummy,bears"` and the options included `"y"`, `"y"` would be checked off because "gummy" has a "y" in it. Changed it to first convert the stringified list and then check to see if the option is in that array, which will do a full comparison of values as strings to the target option string
=> fix multiselect value check

package-lock.json, package.json, src/elements/slider.svelte
Currently our min and max labels are centered over the right and left edges of the slider module. This causes layout problems when used.
Fix:
- Left and right align labels instead, bound to parent container.
=> Slider min/max labels no longer break bounds of parent container

package-lock.json, package.json, src/elements/button/button.svelte, src/elements/input/input.svelte, src/elements/pill.svelte, src/elements/radio.svelte, src/elements/select/multiselect.svelte, src/elements/select/select.svelte, src/elements/slider.svelte, src/elements/switch.svelte, src/stories/multiselect.stories.mdx, src/stories/radio.stories.mdx, src/stories/select.stories.mdx, src/stories/slider.stories.mdx, src/stories/switch.stories.mdx
I have gone through the PRIME elements added readonly states where they didn't exist on any element that the user can input information to. I have also changed all readonly and disabled states to look the same to user by changing the text and background colors, rather than the previous method of changing the opacity of the text and the background. Examples shown below.
input - readonly (top) and disabled (bottom):
multi-select - readonly (top) and disabled (bottom):
=> APP-1162: Give all PRIME Inputs a "readonly" State

package.json, playground/src/Test.vue, playground/src/breadcrumb-test.vue, tests/breadcrumbs.spec.ts
**2023.02.13_APP-1268: Prime Breadcrumbs E2E Tests**
**Items to Note:**
- This PR is comprised of playwright tests to confirm the following behavior for prime breadcrumbs.
Behavior | Scenario
-- | --
Crumbs | GIVEN a "crumbs" attribute has been applied to the v-breadcrumbs element AND the value passed to the "crumbs" attribute is a comma-separated list of strings WHEN the element is rendered THEN the breadcrumbs should render the list of values as pills
<p></p>
=> APP-1268: Prime Breadcrumbs E2E Tests

playground/src/Test.vue, playground/src/icon-test.vue, playground/src/pill-test.vue, tests/Icon.spec.ts, tests/pill.spec.ts
Add icon e2e tests. Also did some reformatting of test file names to keep them standardized.
Test cases covered:
Behavior | Scenario
-- | --
Name | GIVEN a "name" attribute has been applied to thev-icon elementAND the "name" attribute value is a valid icon nameWHEN the element is renderedTHEN the icon should render the appropriate image
Size: default | GIVEN a "size" attribute has not been applied to the v-icon elementWHEN the element is renderedTHEN the icon should render as the base size
Size: xs | GIVEN a "size" attribute has been applied to thev-icon elementAND the "size" attribute value is "xs"WHEN the element is renderedTHEN the icon should render as extra-small
Size: sm | GIVEN a "size" attribute has been applied to thev-icon elementAND the "size" attribute value is "sm"WHEN the …
=> APP-1270 - Icon e2e

playground/src/Test.vue, playground/src/notify-test.vue, tests/notify.spec.ts
Add e2e tests for notify
Test cases:
Behavior | Scenario
-- | --
Title | GIVEN a "title" attribute has been applied to the v-notify elementWHEN the element is renderedTHEN the notify should render the "title" attribute value in the notify title
Message | GIVEN a "message" attribute has been applied to the  v-notify elementWHEN the element is renderedTHEN the notify should render the "message" attribute value in the notify message
Variant: default | GIVEN no "variant" attribute has been applied to the v-notify elementOR the "variant" attribute value is not "error", "warning", "success", or "info"WHEN the element is renderedTHEN the notify should render with a blue borderAND the notify should render with a blue info icon
Variant: error | GIVEN a "variant" attribute has been applied to the …
=> APP-1271 - Notify e2e

src/elements/modal.svelte, src/stories/modal.stories.mdx
Makes the overlay keyboard navigable since we had a keydown event for it, and updates the story to make the close functionality work and clarify what are actual props vs demo only props.
=> Update modal story and make overlay tab navigable

playground/src/App.vue, src/elements/select/utils.ts, src/lib/sort.ts
The bug was that when we add special characters to the v-select, we convert the string to a regex. This means if there are special characters in the string, it will break the component, and ultimately the page. This adds backslashes to any special character in the string, and will treat that as a character to match on rahter than a special character.
=> App 1341: Don't break the select component when adding special chars to the input

playground/code-editor-test.html, playground/src/code-editor-test.ts, playground/src/code-editor-test.vue, src/elements/code-editor.svelte, src/lib/monaco/index.ts, tests/code-editor.spec.ts, tests/select.spec.ts
I had some issues making tests for the monaco editor because monaco does a lot of things under the hood which are hard to determine via CSS.
1. Syntax highlighting - through looking at CSS it's clear that monaco has different styles that it renders for group of text depending on its language & whether its correct syntax. It's unclear what classes match to what combinations for these, so for now I avoided creating tests for syntax highlighting. 
2. Syntax highlighting for incorrect syntax - for the same reason ^ its difficult to know whether the syntax is correct via the css classes for each line in the editor. Looking at the /code-editor-test.html, we can manually inspect whether the syntax is highlighted correctly. I maninly added separate tests for invalid syntax to check that they were …
=> App 1352: Adding component tests for monaco-editor

.github/workflows/pullrequest.yml
The CI runs for #205 and #210 are currently (at the time of writing) failing due to cancellation timeouts. This PR increases the timeout, accordingly.
How does doubling the value seem to everyone?
Ensure CI is green.
=> Increase E2E test timeout in CI

package-lock.json, package.json, src/elements/button/button.svelte, src/elements/input/input.svelte, src/elements/radio.svelte, src/elements/select/multiselect.svelte, src/elements/select/select.svelte
Requesting some PRIME changes as discussed:
button
text-xs px-3 py-1.5 
for buttons with icons, side padding should be pl-2 pr-3 instead of px-3
radio
for the text on the actual switches (not the label): text-xs px-3 py-1.5
input
for the text in the input (not the label): text-xs px-2 py-1.5
select/multiselect
for the text in the input (not the label): text-xs pl-2 py-1.5
for the options in the dropdown panel: text-xs py-1.5
(Basically, just making all the font in those components 12px and adjusting side padding as needed. All the components should remain 30px in height.)
=> design updates

package.json
This prevents users from installing with different package managers. Let's remove it!
=> Remove preinstall pnpm check

playground/src/context-menu-test.vue, playground/src/radio-test.vue, src/elements/pill.svelte, tests/context-menu.spec.ts, tests/input.spec.ts, tests/lib/helper.spec.ts, tests/lib/helper.ts, tests/multi-select.spec.ts, tests/pill.spec.ts, tests/radio.spec.ts, tests/select.spec.ts, tests/slider.spec.ts, tests/switch.spec.ts, tests/tabs.spec.ts, tests/vector-input.spec.ts
This migrates the tests to listen for custom events on the element itself instead of the page.
When migrating to Svelte 4, we will no longer be able to dispatch a custom event that bubbles up the page. (This is consistent with Svelte's event dispatcher that events do not bubble.) To prepare for that, the tests should listen for events on the element itself.
Some of the tests began failing for unknown reasons, particularly those that test "enter" key press. I disabled those tests instead of figuring out why the custom events are not propogating correctly. We will re-enable those tests once the components export Svelte components and we can migrate the tests to use those directly.
=> APP-1996 listen to elements instead of the page in PRIME tests

package.json, src/elements/notification/container.component, src/elements/notification/item.component, src/elements/notification/stores.ts, src/lib/notify.ts
This PR changes the behavior of toasts so that if a duplicate message is pushed, an existing toast will reset its timer and migrate to the top of the list rather than stacking duplicate messages.
=> Reset toast notifications rather than duplicating them

package.json, src/elements/icon/icons.ts, src/stories/icon.stories.mdx
**Adds Duplicate Icon**
Adds a duplicate icon into PRIME.  
Icon necessary for FE work to duplicate a component.
Ticket: https://viam.atlassian.net/browse/APP-419
Figma: https://www.figma.com/file/XLsscBRMdg6kUKHVNSzXOA/Robot-Details-%3E-Config?type=design&node-id=4113-56359&mode=design&t=Dm8En71PgFNrhEtX-0
=> Add duplicate icon

packages/core/src/lib/breadcrumbs.spec.ts, packages/core/src/lib/breadcrumbs.svelte, packages/core/src/lib/index.ts, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/breadcrumbs.stories.mdx
Migrates Breadcrumbs component to `@viamrobotics/prime-core`.
- Copy `breadcrumbs.svelte` to `packages/core`
- Change props to accept an array
- Add `Breadcrumbs` export from `index.ts`
- Copy unit tests
- Change to use vitest
- Copy storybook story to `packages/storybook`
- Change to use Svelte component directly
- Added unit tests
- None
=> APP-2283 Migrate Breadcrumbs to @viamrobotics/prime-core

packages/core/src/lib/badge.svelte
Setting up an example for component documentation 🎉 
Note: it would be cool to somehow export the @component docs to storybook, but haven't thought of a simple way to do that yet.
=> Document badge component

packages/core/package.json, packages/core/src/lib/index.ts, packages/core/src/lib/tooltip.spec.svelte, packages/core/src/lib/tooltip.spec.ts, packages/core/src/lib/tooltip.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/tooltip/plain-text.svelte, packages/storybook/src/stories/tooltip/rich-html.svelte, packages/storybook/src/stories/tooltip/tooltip.stories.mdx, packages/storybook/svelte.config.js, packages/storybook/tsconfig.json, pnpm-lock.yaml
Adds the `<Tooltip />` to `core`. 
Notes:
- The layout for the component has been changed to be accessible. The major changes are there is no singular root component, and the default slot is now nested in an unstyled `<button />` element. This is so that the tooltip target can be focused using keyboard navigation, and so we can use proper `aria` syntax to assist with accessibility. 
- The `text` prop was removed, and now the tooltip text must be passed using the `slot="text"` syntax. This allows using rich html inside of tooltips and removes confusion on which to use.
- Removed the `<style />` block and instead relied on `tailwindcss` classes.
- Added unit tests, will add `e2e` tests for tooltip location in a follow-up that introduces `playwright` to `core`
- Due to the nature of …
=> Add tooltip

packages/core/src/lib/index.ts, packages/core/src/lib/label.spec.svelte, packages/core/src/lib/label.spec.ts, packages/core/src/lib/label.svelte, packages/core/src/lib/tooltip.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/label/label.stories.mdx, packages/storybook/src/stories/label/with-input.svelte
This PR adds a new element to `core`, the `Label`. This is the first step of migrating the `Input` to core, by first breaking it apart from its wrapping `Label` to simplify both components. This PR also includes fixes to the tooltip to make sure it works as expected inside of a `Label` (making sure the tooltip text is not read aloud as a part of the label text.)
=> Add label to core

packages/legacy/package.json, packages/legacy/src/elements/icon/icons.ts, packages/legacy/src/stories/icon.stories.mdx
These icons are needed for the new org settings UI to support location/robot permissions
=> Add resource icons

packages/core/package.json, packages/core/src/lib/context-menu/context-menu-item.svelte, packages/core/src/lib/context-menu/context-menu-separator.svelte, packages/core/src/lib/context-menu/context-menu.spec.svelte, packages/core/src/lib/context-menu/context-menu.spec.ts, packages/core/src/lib/context-menu/context-menu.svelte, packages/core/src/lib/index.ts, packages/core/src/routes/+page.svelte, packages/legacy/src/stories/context-menu.stories.mdx, packages/storybook/src/stories/context-menu/context-menu.stories.mdx, packages/storybook/src/stories/context-menu/context-menu.svelte
Adds the context menu component and related elements `<ContextMenuItem />` and `<ContextMenuSeparator />` to core.
Added stories demonstrating ContextMenuItem and ContextMenuSeparator individually, and one example of all elements together as a full ContextMenu
Removed a test related to tab / enter select behavior, as this is implemented by the browser and not testable with vitest. This should be tested with Playwright when we add it into Prime for larger component testing.
=> APP-2288 Add context menu to core

packages/core/.eslintrc.cjs, packages/core/package.json, packages/core/src/lib/__tests__/click-outside.spec.svelte, packages/core/src/lib/__tests__/click-outside.spec.ts, packages/core/src/lib/click-outside.ts, packages/core/src/lib/index.ts, pnpm-lock.yaml
@DTCurrie and I have been thinking:
- "do something on click outside" is a common thing across our UIs
- [Svelte actions](https://svelte.dev/docs/svelte-action) (custom `use:...` directives) are the most reliable way to implement this, given reactivity and cleanup concerns
- The [classic click outside action example](https://svelte.dev/repl/0ace7a508bd843b798ae599940a91783?version=3.16.7) does not play nicely with TypeScript 
This PR takes as stab at adding a `clickOutside` action to `@viamrobotics/prime-core` in a type-checking-friendly manner.
```svelte
<script lang="ts">
import { writable } from 'svelte/store'
import { clickOutside } from '@viamrobotics/prime-core'
const isOpen = writable(false)
</script>
<button on:click={() => isOpen.set(true)}>
Open Menu
</button>
{#if isOpen} …
```
=> Add use:clickOutside action to prime-core

packages/legacy/package.json, pnpm-lock.yaml
Resolves https://github.com/viamrobotics/prime/pull/342
=> Bump vite in legacy

packages/core/package.json, packages/core/src/lib/__tests__/prevent-handler.spec.svelte, packages/core/src/lib/__tests__/prevent-handler.spec.ts, packages/core/src/lib/breadcrumbs.svelte, packages/core/src/lib/button/button.svelte, packages/core/src/lib/button/icon-button.svelte, packages/core/src/lib/index.ts, packages/core/src/lib/input/text-input.svelte, packages/core/src/lib/prevent-handler.ts, packages/core/src/lib/select/__tests__/select.spec.svelte, packages/core/src/lib/select/__tests__/select.spec.ts, packages/core/src/lib/select/select.svelte, packages/core/src/routes/+page.svelte
I noticed after bumping `prime-core` in app we had some errors popping up around the new event handling. After some experimentation the pattern I used for the `<Select />` seems to be the best way to intercept native event handling without overriding it or forcing custom events. We capture and prevent default and propagation of the event on the capture phase before letting whatever native event was passed to the component do its thing on the bubble phase. Added some tests around that as well.
Also updated the padding around the breadcrumb text to match the padding in designs. I noticed they were wider than expected when using them on the module details page in the viam app.
=> Fix breadcrumb padding and select event handling

packages/core/package.json, packages/core/src/lib/__tests__/banner.spec.svelte, packages/core/src/lib/__tests__/banner.spec.ts, packages/core/src/lib/banner.svelte, packages/core/src/routes/+page.svelte
Reinstating the legacy default slot as the "message" slot, and refactoring the "message" slot to the "subtitle" slot to match its style/intent:
=> Reintroduce default slot behavior from legacy with proper text size

packages/core/package.json, packages/core/src/lib/select/select.svelte
Safari adds a `5px` border radius to selects (because of course it does.) Sharp corners for all!
=> APP-2206 Add rounded-none to select

packages/core/package.json, packages/core/theme.ts
I accidently added a `z-index` prop to the theme's root object, which obliterates all other z-index classes. It's still in `extend`.
=> Fix theme z-indexes

.github/workflows/ci.yml, packages/storybook/package.json
This will make prime.viam.com serve the new Storybook instead. Huzzah!
=> APP-2306 Use new storybook for github pages

packages/core/package.json, packages/core/src/lib/banner.svelte, packages/core/src/lib/button/__tests__/icon-button.spec.ts, packages/core/src/lib/button/button.svelte, packages/core/src/lib/button/icon-button.svelte, packages/core/src/lib/context-menu/context-menu-item.svelte, packages/core/src/lib/icon/icon.svelte, packages/core/src/lib/icon/icons.ts, packages/core/src/lib/index.ts, packages/core/src/lib/input/input.svelte, packages/core/src/lib/radio.svelte, packages/core/src/lib/select/multiselect.svelte, packages/core/src/lib/select/searchable-select.svelte, packages/core/src/lib/select/select-menu.svelte
This is a minor improvement that will hopefully improve quality of life when using icons. Icons now must be one of the available icon names instead of any `string`. Autocomplete will be more helpful and we won't ever ship code that has missing icons!
=> Harden types for icon names

packages/core/package.json, packages/core/src/lib/__tests__/vector-input.spec.ts, packages/core/src/lib/vector-input.svelte, packages/core/src/routes/+page.svelte
Fixes a few minor issues with vector input that emerged due to recent changes:
* Vector input cannot be set as an immutable component, because it depends on object props that in some cases must be mutable
* Vector input should fire `input` and `change` events like the underlying `SliderInput` that it wraps.
=> Vector input fixes

packages/core/src/lib/__tests__/unique-id.spec.ts, packages/core/src/lib/index.ts, packages/core/src/lib/notification/context.ts, packages/core/src/lib/select/multiselect.svelte, packages/core/src/lib/select/searchable-select.svelte, packages/core/src/lib/tooltip/tooltip.svelte, packages/core/src/lib/unique-id.ts, packages/storybook/src/stories/unique-id.mdx, packages/storybook/src/stories/unique-id.stories.svelte
More changes from https://github.com/viamrobotics/prime/pull/357 This one renames `useUniqueId` to `uniqueId` because it is _not_ a hook, and adds a storybook story for `uniqueId`.
=> Rename useUniqueId -> uniqueId

packages/core/package.json, packages/core/src/lib/index.ts, packages/core/src/lib/input/slider-input.svelte, packages/core/src/lib/tooltip/__tests__/tooltip.spec.ts, packages/core/src/lib/tooltip/index.ts, packages/core/src/lib/tooltip/tooltip-container.svelte, packages/core/src/lib/tooltip/tooltip-styles.ts, packages/core/src/lib/tooltip/tooltip-target.svelte, packages/core/src/lib/tooltip/tooltip-text.svelte, packages/core/src/lib/tooltip/tooltip.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/tooltip.mdx, packages/storybook/src/stories/tooltip.stories.svelte
Following up on #381, as I went to integrate the updated Tooltip, I saw that several Svelte usage sites of this tooltip would benefit from the "separate target from described element" work I mentioned in that ticket.
This PR breaks the `<Tooltip>` into its constituent parts:
- `<TooltipContainer>` - a stateful wrapper
- `<TooltipTarget>` - a wrapper that attaches mouse/focus event listeners
- `<TooltipText>` - a presentational tooltip text component
You can continue to use `<Tooltip>`, or if that doesn't work for the UI in question, assemble the three parts however you need. In practice, I think this will mostly be "the visual target is different that the element on which we need to set `aria-describedby`.
I also upgraded the style calculation logic to automatically adjust …
=> APP-2206: break apart tooltip component for custom usage

packages/core/README.md, packages/core/src/lib/button/icon-button.svelte, packages/core/src/lib/input/__tests__/input.spec.ts, packages/core/src/lib/input/input.svelte, packages/core/src/lib/select/__tests__/multiselect.spec.ts, packages/core/src/lib/select/__tests__/searchable-select.spec.ts, packages/core/src/lib/select/__tests__/select.spec.ts, packages/core/src/lib/select/multiselect.svelte, packages/core/src/lib/select/searchable-select.svelte, packages/core/src/lib/select/select-input.svelte, packages/core/src/lib/select/select-menu.svelte, packages/core/src/lib/select/select.svelte, packages/core/theme.ts
Continuing with changes from https://github.com/viamrobotics/prime/pull/357 this replaces the usage of `h-[30px]` and `w-[30px]` arbitrary classes with new utility classes.
=> Add h-7.5 and w-7.5 classes

packages/core/package.json
I must've lost my version bump in a merge. Bumping to get `RestrictedTextInput`.
=> Bump prime-core to 0.0.47

packages/core/package.json, packages/core/src/lib/radio.svelte, packages/core/src/lib/toggle-buttons.svelte
After seeing it in `app` I noticed the margins for the `legend`s were missing, also simplified our ignores for test files so anything in a `__tests__` directory is ignored.
=> Fix toggle button legend margins and ignore all things __tests__

packages/core/README.md, packages/core/src/lib/__tests__/label.spec.svelte, packages/core/src/lib/__tests__/radio.spec.svelte, packages/core/src/lib/__tests__/switch.spec.svelte, packages/core/src/lib/__tests__/toggle-buttons.spec.svelte, packages/core/src/lib/banner/__tests__/banner.spec.svelte, packages/core/src/lib/context-menu/__tests__/context-menu.spec.svelte, packages/core/src/lib/select/__tests__/select.spec.svelte, packages/core/src/lib/table/__tests__/table-row.spec.svelte, packages/core/src/lib/table/__tests__/table.spec.svelte, packages/core/src/lib/tooltip/__tests__/tooltip.spec.svelte
Per some conversation we have decided the docs strings in test components are not providing a lot of value and mostly have become rote copy-and-paste inclusions with new code. I moved the relevant documentation to the README and removed component-level doc strings.
=> Remove redundant test component doc strings and add blurb to README

packages/blocks/package.json, packages/blocks/src/lib/slam-map-2d/axes-helper.svelte, packages/blocks/src/lib/slam-map-2d/helpers.svelte, packages/blocks/src/lib/slam-map-2d/hooks/use-raycast-click.ts, packages/blocks/src/lib/slam-map-2d/hooks/use-raycast-click/__tests__/normalize-device-coordinates.spec.ts, packages/blocks/src/lib/slam-map-2d/hooks/use-raycast-click/index.ts, packages/blocks/src/lib/slam-map-2d/hooks/use-raycast-click/normalize-device-coordinates.ts, packages/blocks/src/lib/slam-map-2d/index.svelte, packages/blocks/src/lib/slam-map-2d/points.svelte, packages/blocks/src/lib/slam-map-2d/scene.svelte, packages/blocks/src/routes/+page.svelte, pnpm-lock.yaml
This PR removes `trzy` as a peer-dep and makes the folllowing replacements:
* Use [`@threlte/extras` Grid](https://threlte.xyz/docs/reference/extras/grid) instead
* Use an internal AxesHelper instead
* Use an internal raycaster for clicking on the slam map
=> Remove trzy dependency from prime-blocks

packages/core/package.json, packages/core/src/lib/icon/icons.ts, packages/storybook/package.json, packages/storybook/src/stories/icon.stories.svelte, pnpm-lock.yaml
Adds the `selection-ellipse` icon. While working on this, I noticed...
- The storybook icon name tooltip was broken, and nobody noticed because
- The storybook stories weren't getting type checked
...so I fixed those, too.
I also learned that I don't know how to spell "ellipse", so please keep an eye out for typos
=> APP-2991: add selection-ellipse icon

packages/core/package.json, packages/core/src/lib/__tests__/code-snippet.spec.ts, packages/core/src/lib/__tests__/use-timeout.spec.svelte, packages/core/src/lib/__tests__/use-timeout.spec.ts, packages/core/src/lib/browser.ts, packages/core/src/lib/code-snippet.svelte, packages/core/src/lib/input/restricted-text-input.svelte, packages/core/src/lib/use-timeout.ts
Per this conversation: https://github.com/viamrobotics/prime/pull/411#discussion_r1370854790
The dark theme does not work well for JSON, which intend to use this code-snippet for frequently. If we want to introduce a dark mode, we should probably think about that more comprehensively.
Also, after we introduced the reactivity statement to rehighligh on code changes, we need to start escaping the `code` passed to this component when setting it as the `innerHtml` of the `element`.
=> Remove code-snippet theme prop

packages/core/package.json, packages/core/src/lib/tooltip/tooltip-styles.ts
I found a situation where floating-ui was not respecting the passed in location. After reading the docs, I found the [combining with shift](https://floating-ui.com/docs/flip#combining-with-shift) section of the `flip` docs:
> If `shift()` is in use in the middleware array, you may desire to disable `crossAxis` overflow checking, which will allow `shift()` to perform its work without falling back to the opposite axis (therefore preserving the original axis as best as possible):
>
> If your placement is not edge aligned, disabling it is usually a good choice.
We use `shift` with `flip`, so this PR follows the doc's advice, which fixes the mispositioning in my testing
=> Fix tooltip positioning

.vscode/settings.json, packages/core/package.json, packages/core/src/lib/button/button.svelte, packages/core/theme.ts, packages/legacy/package.json, packages/legacy/src/elements/button/button.svelte
After talking with Nat, this PR adds two colors to our scale that are common in our codebase and have been popping up in new code: `rgba(0, 0, 0, 0.04)` and `rgba(0, 0, 0, 0.08)` - aka the hover and active variants for the ghost button.
I'm open to whatever names, but I went with `ghost-light` and `ghost-medium`.
- Add `ghost-light` and `ghost-medium` color variants
- Add `.vscode/settings` to git tracking for:
- Use `typescript` from `node_modules`
- Use `prettier` for formatting Svelte
- Use `eslint` for checking Svelte
- Add `cx` prop and `cx()` function to Tailwind intellisense
=> APP-3028: add opaque grey variants

packages/core/package.json, packages/core/src/lib/__tests__/modal.spec.ts, packages/core/src/lib/modal.svelte, packages/core/src/routes/+page.svelte, packages/storybook/.eslintrc.cjs, packages/storybook/src/stories/modal.stories.svelte
When writing the Modal component for prime-core, I suggested we ditch events in favor of the two-way data binding of an `isOpen` store. After some usage in the app, we've discovered this is a pretty awkward API.
This PR switches the modal back to a plain, controlled `isOpen: boolean` prop and a `close` event, which should be more predictable. As a result, this means the modal is no longer capable of closing itself; it must emit the `close` event and the parent must chose to close it.
I think there are continuing improvements to be made here, especially given the awkwardness of combining the `close` event with any buttons placed in the `primary` and `secondary` slots, but I think this is a step in the right direction.
**This is a breaking change to prime-core.** See the companion PR in the …
=> Replace Modal.isOpen with controlled boolean

packages/blocks/package.json, packages/blocks/src/lib/index.ts, packages/blocks/src/lib/navigation-map/components/draw-tool.svelte, packages/blocks/src/lib/navigation-map/components/nav/obstacles.svelte, packages/blocks/src/lib/navigation-map/components/obstacle.svelte, packages/blocks/src/lib/navigation-map/lib/create-obstacle.ts, packages/blocks/src/lib/navigation-map/types.ts, packages/blocks/src/routes/navigation-map.svelte
This is prep to render transient obstacles differently. By making coloring declarative, `blocks` does not need to determine what is a transient obstacle.
- Add color and label to `Obstacle` type
- Update colors used in dev environment - cyberpunk for static and hologram for transient
- Note: app and rdk will need to declare these colors as well
- Obstacles become deselected if they are already clicked
- Render a color chip for each obstacle in the list of obstacles, including a tooltip label
- (cleanup) Export `Plans` type
=> Make obstacle coloring declarative

packages/core/package.json, packages/core/src/lib/context-menu/__tests__/floating-menu.spec.svelte, packages/core/src/lib/context-menu/__tests__/floating-menu.spec.ts, packages/core/src/lib/context-menu/context-menu.svelte, packages/core/src/lib/context-menu/floating-menu.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/context-menu.stories.svelte
This PR makes two changes to the `<FloatingMenu>` component required by work on APP-3122:
- We need to be able to add accessible attributes to the control element to add a tooltip
- We need to control the open state of the menu to set styles properly
=> APP-3122: make floating menu controlled, add aria props

packages/blocks/package.json, packages/blocks/src/lib/navigation-map/components/obstacle.svelte, packages/blocks/src/routes/navigation-map.svelte
This is the lightest touch way to render a point as a sphere. It does not try to render as an actual point or use sizeAttenuation to scale keep the sphere the same size always.
=> RSDK-4028: Render points as a sphere

packages/core/package.json, packages/core/src/lib/tooltip/__tests__/tooltip.spec.svelte, packages/core/src/lib/tooltip/__tests__/tooltip.spec.ts, packages/core/src/lib/tooltip/tooltip-container.svelte, packages/core/src/lib/tooltip/tooltip-styles.ts, packages/core/src/lib/tooltip/tooltip.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/tooltip.mdx, packages/storybook/src/stories/tooltip.stories.svelte
Per the [designs for APP-3124](https://www.figma.com/file/GSi2nRrsKHQnP2uYNx5XMK/Make-UI-Not-Shitty-II?type=design&node-id=3100-16026&mode=design&t=MNU0aepvDubaCdJ1-11), some tooltips should only show after 1s of hovering.
- Add `hoverDelayMS` prop to `Tooltip` and `TooltipContainer`
- Add `hoverDelayMS` writable to tooltip context, and update `isVisible` derived store to set after timeout
- Add test
- Add example to dev environment
- Add example to storybook
=> APP-3124: Add hover delay for tooltips

packages/core/package.json
The purpose of this PR is to bump the prime-core version from `0.0.72` to `0.0.73`
=> APP-2198: Bump prime-core version

packages/core/src/lib/toast/__tests__/toast.spec.ts, packages/core/src/lib/toast/context.ts, packages/core/src/lib/toast/toast-banner.svelte, packages/core/src/lib/toast/toast-container.svelte, packages/storybook/src/stories/use-toast.mdx, packages/storybook/src/stories/use-toast.stories.svelte
In this PR, I made the `provideToast` function easier to use and added some padding to the toast.
=> APP-2198-FIX: Added padding and refactored function

.vscode/settings.json, packages/core/.eslintrc.cjs, packages/core/src/lib/floating/floating-style.ts, packages/core/src/lib/floating/floating.svelte, packages/core/src/lib/icon/index.ts, packages/core/src/lib/index.ts, packages/core/src/lib/input/index.ts, packages/core/src/lib/input/input-state.ts, packages/core/src/lib/input/input.svelte, packages/core/src/lib/input/text-input.svelte, packages/core/src/lib/radio.svelte, packages/core/src/lib/select/__tests__/multiselect.spec.ts, packages/core/src/lib/select/__tests__/search.spec.ts, packages/core/src/lib/select/__tests__/searchable-select.spec.ts, packages/core/src/lib/select/__tests__/select.spec.svelte, packages/core/src/lib/select/index.ts, packages/core/src/lib/select/multiselect.svelte, packages/core/src/lib/select/search.ts, packages/core/src/lib/select/searchable-select.svelte, packages/core/src/lib/select/select-input.svelte, packages/core/src/lib/select/select.svelte
While working on `<SearchableSelect>`, I ran into some fiddly bugs and organizational lint that didn't fit neatly into actually working on `<SearchableSelect>`. I threw them all into this separate PR for easier review.
- Menu toggle button in `<SelectInput>` now set to `type="button"` to avoid errant form submissions
- Scope `<SelectInput>` group modifiers more strictly to avoid weird hover/focus states when inside nested tailwind `group`s
- Prevent `<SelectInput>` button from taking focus away from the `<input>`
- Fix types of `<Floating>` props
- Allow `<SelectInput>` focus styles to be disabled so a `combobox` can maintain DOM focus while [visually focusing elsewhere](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-activedescendant)
- Allow `<Floating>` …
=> APP-3126: clean up various interfaces for searchable select fixes

packages/core/package.json, packages/core/src/lib/index.ts, packages/core/src/lib/keyboard.ts, packages/core/src/lib/select/__tests__/searchable-select.spec.ts, packages/core/src/lib/select/searchable-select.svelte, packages/core/src/lib/select/select-input.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/select.mdx, packages/storybook/src/stories/select.stories.svelte
This rebuilds the `<SearchableSelect>` from the ground up with the following goals:
- Fix a11y of the element so it follows [Editable Combobox With List Autocomplete Example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/) from the ARIA APG
- Elements should be a  `combobox` and `listbox`; currently it is a `combobox` and a `menu`, which turns out, is not correct! (This is also a problem with the resource picker over in app)
- DOM focus should remain in the `<input role="combobox">` while options are highlighted, using `aria-activedescendant` to manage visual/a11y focus
- Keyboard handlers should follow WAI recommendations
- Update props of the component to match needs + actual usage
- Nothing uses the `heading` props, and it wasn't in Figma, so I …
=> APP-3126: fix searchable select value and focus issues

.vscode/settings.json, packages/blocks/vite.config.ts, packages/core/package.json, packages/core/src/lib/select/searchable-select.svelte, packages/core/src/vitest.setup.ts, packages/core/vite.config.ts
Missed a potential SSR bug in `<SearchableSelect>` due to a global mock of `scrollIntoView` in the `prime-core` tests. This PR removes the mock and fixes the bug
=> APP-3126: remove scrollIntoView mock

packages/core/package.json, packages/core/src/lib/floating/floating-size.ts, packages/core/src/lib/floating/floating-style.ts, packages/core/src/lib/floating/floating.svelte, packages/core/src/lib/floating/index.ts, packages/core/src/lib/select/searchable-select.svelte, packages/core/src/lib/tooltip/tooltip-styles.ts, packages/core/src/routes/+page.svelte
There is a bug in the new searchable select if it is rendered in a parent with 0 width (or other changeable size): the floating options list size will be calculated on mount without being updated if the parent's width is later expanded, resulting in the options list being the wrong size in the wrong place.
- Turn on auto-resizing for the `SearchableSelect` options list
- Simplify `Floating` and `floatingStyle` to more directly accept `floating-ui/dom` options
- This will assist some other floating needs in the app
- Code makes sense
- Smoke test the storybook and playground, especially tooltips
- I will be smoke testing against my local app and posting the results here
=> APP-3126: make searchable select autoresize

packages/core/package.json, packages/core/src/lib/index.ts, packages/core/src/lib/toast/context.ts, packages/core/src/lib/toast/toast-banner.svelte, packages/core/src/lib/toast/toast-container.svelte, packages/storybook/src/stories/toast-banner.mdx, packages/storybook/src/stories/toast-banner.stories.svelte
In this PR, I made the following changes to the toast ui element:
- Increased the bottom margin of the toast to `24px`
- Fixed the fade out effect by adding `delay` and `duration`
- Fixed the internal padding of the toast to match the figma designs.
https://github.com/viamrobotics/prime/assets/48206838/4ee2b2f9-8413-4eb9-8399-8946e45416f0
=> APP-2198: Addressing stylistic issues in toast

packages/core/package.json, packages/core/src/lib/icon/icon.svelte
#456 added the `text-gray-6` class to the `<Icon>` component. This, in turn, made it impossible to override the color of an icon with any class that comes later in the Tailwind stylesheet, because `text-gray-6` will always be present, so color will be applied according to CSS specificity.
The PR reverts that addition, which will cause all icons to default to the current text color, fixing several regressions in the app. If we want to default icons to a specific color, we will need to come up with a different approach that conditionally adds a color classname
- Remove `text-gray-6` from icon
=> Do not add a color class to icon

packages/blocks/package.json, packages/blocks/src/lib/slam-map-2d/color-map.ts
This PR makes postprocessed points from the SLAM map  the viam slam brand color "cyberpunk". Regular points only have confidence in the B value, but for postprocessed points we send 100 percent confidence through the red value. Because of this, we can check X and set the color accordingly.
=> RSDK-6218 - make postprocessed slam points the viam slam brand color "cyberpunk"

packages/blocks/package.json, packages/blocks/src/lib/navigation-map/components/nav/waypoints.svelte
[Ticket](https://viam.atlassian.net/browse/RSDK-6093)
Swaps the order of (lng, lat) in the Waypoints tab on the nav RC card.
Before:
After:
=> RSDK-6093 - Fix Lat,Lng order is flipped in nav service rc card

packages/blocks/package.json, packages/blocks/src/lib/slam-map-2d/index.svelte, packages/blocks/src/lib/slam-map-2d/motion-path.svelte, packages/blocks/src/lib/slam-map-2d/scene.svelte, packages/blocks/src/routes/+page.svelte
[Ticket](https://viam.atlassian.net/browse/RSDK-6434) 
1. Change `SlamMap2d`'s motionPath parameter to be of type `Float32Array | undefined` from `string | undefined`
2. Bump `prime/blocks`npm package version
Follow up from https://github.com/viamrobotics/rdk/pull/3450
I confirmed that the output is still the same in the storybook:
=> RSDK-6434 - Refactor the Prime SlamMap2D component to better path type

.vscode/settings.json, packages/core/src/lib/icon/icons.ts, packages/core/src/lib/select/__tests__/searchable-select.spec.ts, packages/core/src/lib/select/searchable-select.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/select.mdx, packages/storybook/src/stories/select.stories.svelte
Back in #459, we made some minor fixes to the `<SearchableSelect>` element:
- Switch from `menu` to `listbox`, as recommended by WAI
- Keep DOM focus on search box, use `aria-activedescendant` for visual focus
- Minor visual fixes (e.g. padding)
- Switch to `floating-ui` for menu placement
This PR adds a `multiple` prop to allow the same `<SearchableSelect>` to be used to select multiple options.
- Add `multiple` prop to `<SearchableSelect>`
- Add `bind`-able `values` prop for use when `multiple={true}`
- Add `onMultiChange` prop for use when `multiple={true}`
- Try out the storybook
- Try out the `core` playground
I did not touch `<Multiselect>` component in this PR. The main difference between the two is that `<Multiselect>` adds pills.
I think we can rework `<Multiselect>` to use …
=> APP-3302: add `multiple` prop to `<SearchableSelect>`

packages/blocks/package.json, packages/blocks/src/lib/navigation-map/components/nav/index.svelte, packages/blocks/src/routes/navigation-map.svelte
In R2D2:
In legacy config:
In control tab:
Padding is definitely wonky in the old UI and control tab, but we're about to get rid of the old UI and the control tab already has a lot of jank.
=> APP-3851: Adjust navigation map spacing

packages/core/package.json, packages/core/src/lib/context-menu/context-menu-item.svelte, packages/core/src/lib/context-menu/floating-menu.svelte, packages/core/src/lib/input/slider-input.svelte, packages/core/src/lib/pill.svelte, packages/core/src/lib/tabs.svelte, packages/core/src/lib/toggle-buttons.svelte
Inside a `<form>`, a `<button>` will implicitly become `type="submit"` if not specified. This is never what we want when using Prime components.
- Specify `type="button"` for every vanilla `<button>` I could find in core
=> APP-3908: ensure all buttons use `<button type="button">`

packages/core/package.json, packages/core/src/lib/select/__tests__/searchable-select.spec.ts, packages/core/src/lib/select/searchable-select.svelte
The `<SearchableSelect>` can trigger an empty `onChange` if you blur it while empty. This PR fixes that bug. It looks like this was a previously existing bad behavior rather than a regression from recent work.
With `value` separated from `searchValue`, the internal `previousValue` variable is no longer needed. Removing it fixes the bug
- Code changes make sense
- Test additions make sense
=> APP-4319: do not trigger an empty onChange from `SearchableSelect`

packages/core/package.json, packages/core/src/lib/floating/floating-size.ts, packages/core/src/lib/floating/floating-style.ts, packages/core/src/lib/floating/floating.svelte, packages/core/src/lib/floating/index.ts, packages/core/src/lib/index.ts
We have floating menus that must not overflow the screen. This PR adds various options to our `floating-ui` wrappers to allow the height of a floating element to be constrained.
- Add `limitHeight` helper to construct `size` options to limit an element's height to the available space, less some margin
- Allow a floating element to use the `position: fixed` strategy, in case a floating element needs to break out of a clipping element
- This happens when a floating element is floating off another floating element with a constrained height with `overflow` set
- Add a `<Floating>` component to take extra classnames
I've got this branch `pnpm link`'d up to my local dev environment to verify this works as intended. Code review should suffice here
=> APP-4460: allow the height of a floating element to be constrained

.github/workflows/ci.yml, package.json
As discussed in Slack. We don't contribute to `legacy` anymore, so this will give us a significant CI speedup
=> Remove legacy playwright tests from CI

packages/core/package.json, packages/core/src/lib/tooltip/tooltip-container.svelte, packages/core/src/lib/tooltip/tooltip-styles.ts, packages/core/src/lib/tooltip/tooltip-target.svelte, packages/core/src/lib/tooltip/tooltip-text.svelte
We don't need to keep tooltip positions up to date if they're not visible. Auto positioning seems relatively expensive (`scroll` listeners, `ResizeObservers`, etc.). This PR turns them off when the tooltip target is not visible
- Auto positioning works when tooltips are visible due to hover
- Auto positioning works when tooltips are visible due to props
=> Disable tooltip auto-positioning when not visible

packages/core/package.json, packages/core/src/lib/select/select.svelte
Clicking on the icon currently makes the arrow spin and doesn't show options. This allows to click through said icon.
Note that the icon does not spin but I don't think it's worth fixing as we're replacing this with a library. Please advise?
https://github.com/viamrobotics/prime/assets/17263/26c271b8-b1cf-4dd6-9be2-54755edfecd1
https://github.com/viamrobotics/prime/assets/17263/e7017acf-8259-45bb-8aca-5ac262c17fb0
=> allow click through

packages/core/package.json, packages/core/src/lib/input/__tests__/restricted-text-input.spec.ts, packages/core/src/lib/tooltip/__tests__/tooltip.spec.ts, packages/core/src/lib/tooltip/tooltip-text.svelte
This PR fixes a frustrating layout issue caused by #509 
- The position of invisible tooltips is not recalculated on screen resize etc.
- Tooltips are hidden via `visibility: invisible`, so they are still in the flow
- If the screen is resized, tooltips will remain where they are, creating overflow
- Swap `visibility: invisible` for `display: hidden` for invisible tooltips
Both `visibility: invisible` and `display: hidden` are invisible to screen-readers. For tooltips that provide `aria-describedby` or `aria-labelledby`, this may not be optimal. Experimenting with VoiceOver seems to indicate that we have a lot of accessibility tuning to do with tooltips, anyway
Try to break this! Throwing a `display: hidden` on there means that we rely on the `display: hidden` getting removed from the …
=> APP-4361: remove tooltips from flow when invisible

packages/core/package.json, packages/core/src/lib/breadcrumbs.svelte, packages/core/src/lib/pill.svelte, packages/core/src/lib/tooltip/tooltip-text.svelte, packages/core/src/routes/+page.svelte
- Tailwind's `truncate` class added
- Fix issue where long tooltips get clipped in favor of wrapping
=> App 4656 add ability to truncate breadcrumb items and pills

packages/core/package.json, packages/core/src/lib/label.svelte, packages/core/src/routes/+page.svelte
Add option to add `for` attribute for use with inputs that are not children. This allows for independent click targets and avoids bug as shown here.
=> add optional for attribute to Label component

packages/core/package.json, packages/core/src/lib/select/searchable-select.svelte, packages/core/src/lib/select/select-input.svelte, packages/core/src/routes/+page.svelte
- add the `id` attribute to the `input` for use with parent label `for` attribute
=> Add id to searchable select

packages/core/package.json, packages/core/src/lib/select/__tests__/searchable-select.spec.ts, packages/core/src/lib/select/searchable-select.svelte, packages/core/src/lib/select/select-input.svelte, packages/core/src/lib/use-next-frame.ts
This PR fixes two performance issues with `<SearchableSelect>` that are having a drastic impact on the app:
- A non-string key is used for the `{#each}` block that renders the options
- This causes Svelte to very eagerly remove and replace DOM elements during updates
- The menu (and its `{#each}`) are rendered even when the menu is closed - hidden via a `display:hidden`
- This causes Svelte to run expensive re-render logic when the menu is neither visible nor accessible
This PR fixes these two issues for a noticeable performance improvement in app pages where several `<SearchableSelect>` elements are rendered.
The change in indentation level blew up the diff a little. There are exactly three changes to `<SearchableSelect>`:
- The menu is now wrapped in an `{#if isExapanded}`
- The `<ul>` …
=> APP-4651: do not render `<SearchableSelect>` list when collapsed

packages/core/package.json, packages/core/src/lib/button/button.svelte, packages/core/src/lib/button/icon-button.svelte, packages/core/src/lib/toast/__tests__/toast.spec.ts, packages/core/src/lib/toast/toast-banner.svelte, packages/core/src/lib/toast/variants.ts, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/toast-banner.mdx, packages/storybook/src/stories/toast-banner.stories.svelte, packages/storybook/src/stories/use-toast.mdx, packages/storybook/src/stories/use-toast.stories.svelte
Currently there is only a success toast variant. This PR creates 4 more toast variants: warn, danger, info, and neutral in accordance with [Figma](https://www.figma.com/design/ERHSYDGTXiEQOVGY8ORg6I/PRIME?node-id=2650-4380&t=JEKiEAXH14oyuHHr-0). It also makes edits to the existing toast design to be in line with Figma as well. 
**Note:** One test had to be edited to use `getByText` instead of `getByRole` as the aria-label for the action button of the toast banner was removed.
=> [APP-5332] [APP-4147]: Add 4 more toast styles and update storybook

packages/core/package.json, packages/core/src/lib/toast/toast-banner.svelte, packages/core/src/lib/toast/variants.ts, packages/storybook/README.md
This PR adds truncation to the text of a toast.
Note: this change is possible as all of the toast verbiage has the format "{action} {name}", like "created test" or "renamed test". So there will be no issues with the action being cut off at the end.
=> [APP-4882] - get toast message to truncate when overflowing

packages/core/package.json, packages/core/src/lib/breadcrumbs.svelte
In support of disabled resources, allow `<Breadcrumbs>` to render with `text-disabled` instead of `text-default`
=> APP-5548: allow breadcrumbs render in text-disabled

packages/core/README.md, packages/core/package.json, packages/core/src/lib/__fixtures__/index.ts, packages/core/src/lib/toast/context.ts
Bring the "no fixture component needed" context testing model to Prime for toasts
Any additional documentation that you think would be helpful?
=> Test: add `createToastContext` fixture

packages/blocks/package.json, packages/blocks/src/lib/slam-map-2d/motion-path.svelte
Lines were missing, turns out they had a minuscule width! Now rendering properly:
=> APP-6034: Fix slam path linewidth

packages/core/package.json, packages/core/src/lib/__tests__/badge.spec.ts, packages/core/src/lib/badge.svelte, packages/core/src/lib/progress/progress.svelte, packages/core/src/routes/+page.svelte
Adding a progress variant of the Badge that includes the `Progress` spinner
=> DATA-3167 add progress variant of badge

packages/core/package.json, packages/core/src/lib/select/searchable-select.svelte, packages/core/src/routes/+page.svelte
I know we are deprecating `SearchableSelect`. However, the `video-path` dropdown for the webcam component builder has caused me enough emotional pain to just come fix this. Thoughts?
Before:
After:
=> Break words in SearchableSelect value & description

packages/core/package.json, packages/core/src/lib/select/searchable-select.svelte
Fix default font size for searchable select.
=> App 6327 searchable select font size

packages/core/package.json, packages/core/src/lib/context-menu/context-menu.svelte, packages/core/src/lib/select/searchable-select.svelte
Didn't add a test because I don't know a good way to add phony elements to the screen in vitest+svelte. (without a SearchableSelect.spec.svelte)
Is there a good way to do this?
=> SearchableSelect LabelledBy Attribute

packages/core/package.json, packages/core/src/lib/select/searchable-select.svelte
:face_exhaling: Oops.
Actually tested by bringing this into app this time.
=> Searchable select described by vs labelled by

packages/core/package.json, packages/core/src/lib/__tests__/toggle-button.spec.ts, packages/core/src/lib/toggle-buttons.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/toggle-buttons.stories.svelte
For teleop, `ToggleButtons` get used for page navigation. When the user flips from `Edit -> Monitor`, the workspace gets saved. If there is an error while saving, we do not want to navigate to `Monitor`. Because the `ToggleButtons` set internal state, it appears as if toggling was successful. This makes the `ToggleButtons` purely presentational so that they only update when the parent changes the `selected` prop.
This will certainly be a breaking change somewhere when we bring it into App. I will do this PRIME upgrade myself and be sure to check all instances.
- Remove internal `selected` state from `ToggleButtons`
- Update tests
- Update storybook
=> APP-6324: Make ToggleButtons purely presentational

packages/core/package.json, packages/core/src/lib/notification/notification-container.svelte
Banner is now shown above objects instead of below.
=> added z-index to useNotify banner

packages/core/package.json, packages/core/src/lib/__tests__/pill.spec.ts, packages/core/src/lib/pill.svelte
- The `<Pill>` component can take an `href`
- If an `href` is provided, the `target` attribute of the anchor defaults to `_blank`
- If a consumer does not want to open the link in a new tab, they add `target="_self"`
- `_self` causes SvelteKit to trigger a full page reload instead of client-side routing
- Intentional, but undocumented behavior from SK, according to an old GH thread in Sapper
- See how clicking on parts and machines from the "All Machines Dashboard" reloads the page instead of preloading and rendering in
This PR removes the default `_blank` and sets it to `undefined`, which will be a more reliable default. A couple call-sites will need to be updated, but otherwise most existing call-sites that rely on the `_blank` default already specify it explicitly.
Check that above …
=> Fix: allow pill anchor target to remain unspecified

packages/blocks/package.json, packages/blocks/src/lib/maplibre/controls/follow.svelte, packages/blocks/src/lib/navigation-map/components/draw-tool.svelte, packages/blocks/src/lib/navigation-map/components/map.svelte, packages/blocks/src/lib/navigation-map/components/obstacle.svelte, packages/blocks/src/lib/navigation-map/components/scene-layer.svelte, packages/blocks/src/lib/navigation-map/components/scene.svelte, packages/blocks/src/lib/navigation-map/index.svelte, packages/blocks/src/lib/slam-map-2d/points.svelte, packages/blocks/src/lib/slam-map-2d/scene.svelte, packages/blocks/src/routes/navigation-map.svelte
This PR gets rid of Threlte imports that have been removed in v8 - the Svelte 5 compatible version.
This is part of a larger slow effort to move us to be ready to upgrade to Svelte 5.
There's actually only one removed import here, and it has to do with event dispatching. Callback props ftw!
=> Prepare Threlte for Svelte 5 upgrade

packages/core/package.json, packages/core/src/lib/__tests__/code-snippet.spec.ts, packages/core/src/lib/code-snippet.svelte, packages/core/src/lib/highlight-code/highlight-code.ts, packages/core/src/lib/highlight-code/index.ts, packages/core/src/lib/highlight-code/prism.ts, packages/core/src/lib/highlight-code/viam-prism-theme.css, packages/core/src/lib/index.ts, packages/core/src/lib/modal.svelte, packages/core/src/routes/+page.svelte, packages/storybook/src/stories/code-snippet.stories.svelte
@ehhong and I noodling on Prism stuff
---
Creating a Svelte action to handle code highlighting with Prism to modularize Prism logic and reuse logic between markdown component (in app) and code snippet element (in Prime).
=> APP-7173: Add Prism code highlighting action

packages/core/theme.ts
Add colors to our theme for syntax highlighting so that we have something to use in situations where we are not using codemirror but want it to be visually consistent.
=> DATA-3601 Add code colors

packages/core/package.json, packages/core/src/lib/__tests__/click-outside.spec.ts, packages/core/src/lib/click-outside.ts
In browsers, if a click `mousedown` starts in one element and `mouseup` ends in another element, the `click` event is fired on the lowest common ancestor of the two elements.
> If the button is pressed on one element and the pointer is moved outside the element before the button is released, the event is fired on the most specific ancestor element that contained both elements
[MDN - click event](https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event)
In most cases, this ancestor is going to trigger our `clickOutside` logic, resulting in frustrating user experiences, especially when selecting text.
Swap `click` listener for `mousedown` and `mouseup` listeners using the same "is target outside?" logic. If and only if both events are outside the target element, the handler is …
=> APP-6535: only fire clickOutside if click starts and ends outside

.github/workflows/ci.yml
CI is currently failing in `main`, this PR fixes it. Follow up to #612
=> CI: remove `deploy-pages` job so CI does not fail

packages/core/package.json, packages/core/src/lib/icon/icon.svelte, packages/core/src/lib/icon/icons.ts, packages/core/src/lib/icon/index.ts
After chatting in dev jam and reviewing a draft PR, it looks like exposing this path data directly will be useful for markdown-based UIs in the app
=> Feat: export icon path data for direct usage in non-Svelte UIs

packages/blocks/package.json, packages/blocks/src/lib/maplibre/index.svelte, packages/blocks/src/lib/maplibre/style.ts, packages/blocks/src/lib/maplibre/zoom.ts
After adding google maps and playing with the satellite layer we are seeing weird behaviors based on the zoom level. We noticed the max zoom values were not being set consistently across the tile styles and the `Map` object we instantiate. This PR aims to align those values.
=> sync max zoom for map code
